Repository yorkie-team/yorkie-ios-sdk, pull requests merged in 2022-11, with the labels that each got.

#27 Add JSONArrays and unit tests for Document
  .swiftlint.yml
  Sources/Document/CRDT/CRDTArray.swift
  Sources/Document/CRDT/CRDTRoot.swift
  Sources/Document/DocEvent.swift
  Sources/Document/Document.swift
  Sources/Document/Json/ElementConverter.swift
  Sources/Document/Json/JSONArray.swift
  Sources/Document/Json/JSONDatable.swift
  Sources/Document/Json/JSONObject.swift
  Sources/Util/Heap.swift
  Sources/Util/Optional+Extensions.swift
  Sources/Util/Trie.swift
  Tests/Document/CRDT/CRDTRootTests.swift
  Tests/Document/Change/ChangeIDTests.swift
  Tests/Document/Change/ChangeTests.swift
  Tests/Document/DocumentTests.swift
  Tests/Document/JSONArrayTests.swift
  Tests/Document/JSONObjectTests.swift
  Tests/Document/Operation/AddOperationTests.swift
  Tests/Document/Operation/MoveOperationTests.swift
  Tests/Document/Operation/RemoveOperationTests.swift
  Tests/Document/Operation/SetOperationTests.swift
  Yorkie.xcodeproj/project.pbxproj
Labels: enhancement 🌟

#28 Create ExampleApp and fix some bugs
  Example/Example.xcworkspace/contents.xcworkspacedata
  Example/Example.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  Example/Example.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Example/ExampleApp/ExampleApp.xcodeproj/project.pbxproj
  Example/ExampleApp/ExampleApp.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  Example/ExampleApp/ExampleApp.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  Example/ExampleApp/ExampleApp/AppDelegate.swift
  Example/ExampleApp/ExampleApp/Assets.xcassets/AccentColor.colorset/Contents.json
  Example/ExampleApp/ExampleApp/Assets.xcassets/AppIcon.appiconset/Contents.json
  Example/ExampleApp/ExampleApp/Assets.xcassets/Contents.json
  Example/ExampleApp/ExampleApp/Base.lproj/LaunchScreen.storyboard
  Example/ExampleApp/ExampleApp/Base.lproj/Main.storyboard
  Example/ExampleApp/ExampleApp/Info.plist
  Example/ExampleApp/ExampleApp/SceneDelegate.swift
  Example/ExampleApp/ExampleApp/ViewController.swift
  Sources/Document/CRDT/CRDTArray.swift
  Sources/Document/Json/JSONArray.swift
  Tests/Document/JSONArrayTests.swift
Labels: enhancement 🌟

#29 Change Document from class to actor for concurrent access to it
  Sources/Document/CRDT/RGATreeList.swift
  Sources/Document/Change/Change.swift
  Sources/Document/Change/ChangePack.swift
  Sources/Document/Document.swift
  Sources/Document/Json/JSONArray.swift
  Sources/Document/Json/JSONObject.swift
  Sources/Document/Operation/RemoveOperation.swift
  Sources/Document/Time/TimeTicket.swift
  Tests/Document/DocumentConcurrentAccessTests.swift
  Tests/Document/DocumentTests.swift
  Tests/Document/JSONArrayTests.swift
  Tests/Document/JSONObjectTests.swift
  Yorkie.xcodeproj/project.pbxproj
Labels: enhancement 🌟

#30 Add Kanban board to ExampleApp & Improve the interfaces of JSONObject and JSONArray
  Example/ExampleApp/ExampleApp.xcodeproj/project.pbxproj
  Example/ExampleApp/ExampleApp/AppDelegate.swift
  Example/ExampleApp/ExampleApp/Kanban/KanbanCard.swift
  Example/ExampleApp/ExampleApp/Kanban/KanbanColumn.swift
  Example/ExampleApp/ExampleApp/Kanban/KanbanViewModel.swift
  Example/ExampleApp/ExampleApp/Kanban/View/KanbanLayoutProperty.swift
  Example/ExampleApp/ExampleApp/Kanban/View/KanbanViewCardCell.swift
  Example/ExampleApp/ExampleApp/Kanban/View/KanbanViewColumnFooter.swift
  Example/ExampleApp/ExampleApp/Kanban/View/KanbanViewColumnHeader.swift
  Example/ExampleApp/ExampleApp/Kanban/View/KanbanViewController.swift
  Example/ExampleApp/ExampleApp/SceneDelegate.swift
  Example/ExampleApp/ExampleApp/Utils/UIColor+Extensions.swift
  Example/ExampleApp/ExampleApp/Utils/UILabelWithPadding.swift
  Example/ExampleApp/ExampleApp/ViewController.swift
  Sources/Document/CRDT/CRDTArray.swift
  Sources/Document/DocEvent.swift
  Sources/Document/Document.swift
  Sources/Document/Json/JSONArray.swift
  Sources/Document/Json/JSONObject.swift
  Sources/Document/Time/TimeTicket.swift
  Sources/Document/Util/YorkieJSONObjectable.swift
  Sources/Util/RedBlackTree.swift
  Tests/Document/DocumentConcurrentAccessTests.swift
  Tests/Document/DocumentTests.swift
  Tests/Document/JSONArrayTests.swift
  Tests/Document/JSONObjectTests.swift
  Tests/Document/Util/YorkieJSONObjectableTests.swift
  Yorkie.xcodeproj/project.pbxproj
Labels: enhancement 🌟

#32 Sync Kanban app with a local server and fix some bugs
  Example/ExampleApp/ExampleApp.xcodeproj/project.pbxproj
  Example/ExampleApp/ExampleApp/Kanban/KanbanCard.swift
  Example/ExampleApp/ExampleApp/Kanban/KanbanColumn.swift
  Example/ExampleApp/ExampleApp/Kanban/KanbanViewModel.swift
  Sources/Core/Client.swift
  Sources/Core/ClientEvent.swift
  Sources/Document/Document.swift
  Sources/Document/Time/ActorID.swift
Labels: bug 🐞, enhancement 🌟

#33 Change some types from class to struct to avoid data racing
  Sources/Document/Change/Change.swift
  Sources/Document/Change/ChangePack.swift
  Sources/Document/Document.swift
  Sources/Document/Operation/AddOperation.swift
  Sources/Document/Operation/MoveOperation.swift
  Sources/Document/Operation/Operation.swift
  Sources/Document/Operation/RemoveOperation.swift
  Sources/Document/Operation/SetOperation.swift
  Tests/Document/Change/ChangeTests.swift
Labels: enhancement 🌟

#35 Apply styles for Swift
  Sources/API/Converter.swift
  Sources/Core/Client.swift
  Sources/Document/CRDT/CRDTArray.swift
  Sources/Document/CRDT/CRDTElement.swift
  Sources/Document/CRDT/CRDTObject.swift
  Sources/Document/CRDT/CRDTRoot.swift
  Sources/Document/CRDT/Primitive.swift
  Sources/Document/CRDT/RGATreeList.swift
  Sources/Document/CRDT/RHT.swift
  Sources/Document/CRDT/RHTPQMap.swift
  Sources/Document/Change/Change.swift
  Sources/Document/Change/ChangeID.swift
  Sources/Document/Change/ChangePack.swift
  Sources/Document/Change/Checkpoint.swift
  Sources/Document/Document.swift
  Sources/Document/Json/JSONArray.swift
  Sources/Document/Json/JSONObject.swift
  Sources/Document/Json/ObjectDataHandler.swift
  Sources/Document/Operation/AddOperation.swift
  Sources/Document/Operation/MoveOperation.swift
  Sources/Document/Operation/Operation.swift
  Sources/Document/Operation/RemoveOperation.swift
  Sources/Document/Operation/SetOperation.swift
  Sources/Document/Time/TimeTicket.swift
  Sources/Util/SplayTree.swift
  Tests/API/V1/ConverterTests.swift
  Tests/Document/CRDT/CRDTArrayTests.swift
  Tests/Document/CRDT/CRDTElementTests.swift
  Tests/Document/CRDT/CRDTObjectTests.swift
  Tests/Document/CRDT/CRDTRootTests.swift
  Tests/Document/CRDT/RGATreeListTests.swift
  Tests/Document/CRDT/RHTPQMapTests.swift
  Tests/Document/Change/ChangeContextTests.swift
  Tests/Document/Change/ChangeIDTests.swift
  Tests/Document/Change/ChangePackTests.swift
  Tests/Document/Change/ChangeTests.swift
  Tests/Document/Change/CheckpointTests.swift
  Tests/Document/DocumentTests.swift
  Tests/Document/JSONArrayTests.swift
  Tests/Document/JSONObjectTests.swift
  Tests/Document/Operation/AddOperationTests.swift
  Tests/Document/Operation/MoveOperationTests.swift
  Tests/Document/Operation/RemoveOperationTests.swift
  Tests/Document/Operation/SetOperationTests.swift
  Tests/Util/SplayTreeTests.swift
Labels: enhancement 🌟

#34 Convert Client from class to actor for concurrency.
  Sources/Core/Client.swift
  Tests/Core/ClientTests.swift
  Tests/Integration/ClientIntegrationTests.swift
Labels: enhancement 🌟

#36 Change endian of Primitive values to little endian
  Sources/API/Converter.swift
  Sources/Document/CRDT/Primitive.swift
Labels: bug 🐞

#37 Improve Document sync Test.
  Sources/API/Converter.swift
  Sources/Document/CRDT/Primitive.swift
  Tests/Integration/ClientIntegrationTests.swift
Labels: enhancement 🌟

#38 Add get(keyPath:) to JSONObject
  Sources/Document/Json/JSONArray.swift
  Sources/Document/Json/JSONObject.swift
  Sources/Document/Util/JSONObjectable.swift
  Tests/Document/JSONObjectTests.swift
  Tests/Document/Util/YorkieJSONObjectableTests.swift
  Yorkie.xcodeproj/project.pbxproj
Labels: enhancement 🌟

#41 Add a github action to publish API reference docs
  .github/workflows/add-release-assets.yml
  .github/workflows/gh-pages.yml
  Package.resolved
  Package.swift
Labels: documentation 📔, enhancement 🌟

#42 Apply changed comments of JS-SDK
  Sources/Document/CRDT/CRDTArray.swift
  Sources/Document/CRDT/CRDTElement.swift
  Sources/Document/CRDT/CRDTObject.swift
  Sources/Document/CRDT/CRDTRoot.swift
  Sources/Document/CRDT/RGATreeList.swift
  Sources/Document/Change/ChangePack.swift
  Sources/Document/Change/Checkpoint.swift
  Sources/Document/DocEvent.swift
  Sources/Document/Document.swift
  Sources/Document/Operation/AddOperation.swift
  Sources/Document/Operation/MoveOperation.swift
  Sources/Document/Operation/Operation.swift
  Sources/Document/Operation/RemoveOperation.swift
  Sources/Document/Operation/SetOperation.swift
  Sources/Document/Util/JSONObjectable.swift
  Tests/Unit/Document/Operation/MoveOperationTests.swift
Labels: documentation 📔

#43 Change eventStream of Client from Error to Never
  Sources/Core/Client.swift
  Tests/Integration/ClientIntegrationTests.swift
  Tests/Unit/Core/ClientTests.swift
  Tests/Unit/Document/DocumentTests.swift
Labels: enhancement 🌟
